[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "prague"
viaIR = true
optimizer = true
optimizer_runs = 1000000
remappings = ["solady/=lib/solady/src/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
base = "https://mainnet.base.org"
baseSepolia = "https://sepolia.base.org"
ethereum = "https://ethereum.publicnode.com"
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
polygon = "https://polygon-rpc.com"
polygonAmoy = "https://rpc-amoy.polygon.technology"
monadTestnet = "https://testnet-rpc.monad.xyz/"
celo = "https://forno.celo.org"
arbitrum = "https://arb1.arbitrum.io/rpc"

[etherscan]
baseSepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
base = { key = "${ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api" }
ethereum = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api" }
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
polygon = { key = "${ETHERSCAN_API_KEY}", url = "https://api.polygonscan.com/api" }
polygonAmoy = { key = "${ETHERSCAN_API_KEY}", url = "https://api-amoy.polygonscan.com/api" }
arbitrum = { key = "${ETHERSCAN_API_KEY}", url = "https://api.arbiscan.io/api" }